{
 "title": "Hello demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "servlet",
    "query": "{__name__=~\"vendor:servlet.*_response_time_total_seconds\"}"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available CPU Processors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_availableProcessors",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load Percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU System Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Memory Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Heap Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(base_memory_usedHeap_bytes/base_memory_maxHeap_bytes)",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Time per Global GC Cycle [[dur]] moving average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds[[dur]]) / rate(base_gc_total[[dur]])",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Other JVM Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "JVM Uptime",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "base_jvm_uptime_seconds" },
    {}
   ]
  }
 ]
}