{
 "title": "MicroProfile Fault Tolerance",
 "description": "Displays metrics collected by methods annotated with MicroProfile Fault Tolerance annotations",
 "tags": [ "microprofile" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "Method",
    "query": "{__name__=~\"application:ft_.*_invocations_total\"}"
   },
   { "name": "avg_period", "label": "Moving Average", "query": "30s, 1m, 3m, 5m, 10m" }
  ]
 },
 "panels": [
  { "title": "Basic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Invocations [per second, avg $avg_period]",
   "type": "graph",
   "description": "Number of method invocations which occurred per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "method",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_invocations_total[$avg_period])",
     "legendFormat": "$method invocations"
    }
   ]
  },
  {
   "title": "Failure rate [%, avg $avg_period]",
   "type": "graph",
   "description": "Percentage of calls which resulted in a failure\n\nThis graph is showing failures after all fault tolerance processing has taken place (including fallback)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_failed_invocations_total[$avg_period]) * 100\n / \nrate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_invocations_total[$avg_period])",
     "legendFormat": "$method"
    }
   ]
  },
  { "title": "Fallback Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Fallback Rate [%, avg $avg_period]",
   "type": "graph",
   "description": "Percentage of method invocations which resulted in the fallback method or handler being called.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_fallback_calls_total[$avg_period]) * 100\n / \nrate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_invocations_total[$avg_period])"
    }
   ]
  },
  { "title": "Retry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Retries per invocation [avg $avg_period]",
   "type": "graph",
   "description": "Average number of retries which occurred for each method invocation.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_retry_retries_total[$avg_period])\n / \n(\n   rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_retry_callsSucceededNotRetried_total[$avg_period])\n + rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_retry_callsSucceededRetried_total[$avg_period])\n + rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_retry_callsFailed_total[$avg_period])\n)",
     "legendFormat": "Retries per invocation"
    }
   ]
  },
  { "title": "Timeout Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Execution duration [s]",
   "type": "graph",
   "description": "Shows quantiles and mean of execution times using a weighted average of the last 1000 executions.\n\nThe quantiles should be understood like this: if the 0.99 quantile is 300ms, then 99% of executions took less than 300ms. (Conversely, 1% of executions took longer than 300ms)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_timeout_executionDuration / 1000",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_timeout_executionDuration_mean / 1000",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Invocations Timed Out [%, avg $avg_period]",
   "type": "graph",
   "description": "Percentage of invocations which timed out",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_timeout_callsTimedOut_total[$avg_period]) * 100\n/\n(\n  rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_timeout_callsTimedOut_total[$avg_period])\n+ rate(application_ft_vlc_emergingtech_quarkus_observable_GreetingResource_hello_timeout_callsNotTimedOut_total[$avg_period])\n)"
    }
   ]
  },
  {
   "title": "Bulkhead Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bulkhead Average Concurrent Calls",
     "type": "graph",
     "description": "Estimate of the number of concurrent calls that are attempted through the bulkhead.\n\nThis is done by multiplying the number of attempted invocations by the mean execution time.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short", "label": "Concurrent attempts" }
     ],
     "targets": [
      {
       "expr": "(\n   rate(application:ft_[[method]]_bulkhead_calls_rejected_total[1m])\n + rate(application:ft_[[method]]_bulkhead_calls_accepted_total[1m])\n)\n *\napplication:ft_[[method]]_bulkhead_execution_duration_mean_seconds"
      }
     ]
    },
    {
     "title": "Bulkhead Execution Time [s]",
     "type": "graph",
     "description": "Shows quantiles and mean of execution times using a weighted average of the last 1000 executions.\n\nThe quantiles should be understood like this: if the 0.99 quantile is 300ms, then 99% of executions took less than 300ms. (Conversely, 1% of executions took longer than 300ms)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "application:ft_[[method]]_bulkhead_execution_duration_seconds",
       "legendFormat": "{{quantile}} quantile"
      },
      {
       "expr": "application:ft_[[method]]_bulkhead_execution_duration_mean_seconds",
       "legendFormat": "Mean"
      }
     ]
    },
    {
     "title": "Bulkhead Rejected Calls [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of calls which were rejected because the bulkhead was full.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(application:ft_[[method]]_bulkhead_calls_rejected_total[$avg_period]) * 100\n / \n(\n   rate(application:ft_[[method]]_bulkhead_calls_rejected_total[$avg_period])\n + rate(application:ft_[[method]]_bulkhead_calls_accepted_total[$avg_period])\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breaker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Circuit Breaker State",
     "type": "graph",
     "description": "Shows how much time the circuit breaker is spending in each of the Closed, Open and Half Open states.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Percentage" }
     ],
     "targets": [
      {
       "expr": "irate(application:ft_[[method]]_circuitbreaker_open_total_seconds[1m])",
       "legendFormat": "Open %"
      },
      {
       "expr": "irate(application:ft_[[method]]_circuitbreaker_half_open_total_seconds[1m])",
       "legendFormat": "Half Open %"
      },
      {
       "expr": "irate(application:ft_[[method]]_circuitbreaker_closed_total_seconds[1m])",
       "legendFormat": "Closed %"
      }
     ]
    },
    {
     "title": "Circuit Breaker Run but Failed [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of invocations which were permitted to run by the circuit breaker but failed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "repeat": "method",
     "yaxes": [
      { "format": "short", "label": "Failure %" }
     ],
     "targets": [
      {
       "expr": "irate(application:ft_[[method]]_circuitbreaker_calls_failed_total[$avg_period]) * 100\n / \n(\n   irate(application:ft_[[method]]_circuitbreaker_calls_failed_total[$avg_period])\n + irate(application:ft_[[method]]_circuitbreaker_calls_succeeded_total[$avg_period])\n)",
       "legendFormat": "Failure %"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Hello Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "servlet",
    "query": "{__name__=~\"vendor:servlet.*_response_time_total_seconds\"}"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available CPU Processors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_availableProcessors",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load Percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU System Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Memory Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Heap Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(base_memory_usedHeap_bytes/base_memory_maxHeap_bytes)",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Time per Global GC Cycle [[dur]] moving average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds[[dur]]) / rate(base_gc_total[[dur]])",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Other JVM Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "JVM Uptime",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "base_jvm_uptime_seconds" },
    {}
   ]
  }
 ]
}